<?php
namespace app\api\controller;
use app\api\controller\base\BaseController;
use think\facade\Log;
use think\facade\Request;
use think\Exception;
use think\Db;
use think\facade\Cache;
use app\common\model\UserModel;
use app\common\model\BillinfoModel;
use app\common\model\ReceiptModel;
use app\common\model\ProductModel;
use app\common\model\ProductHaveModel;
use GuzzleHttp\json_encode;
class IospayController extends BaseController
{
	/**
      * 21000 App Store不能读取你提供的JSON对象
      * 21002 receipt-data域的数据有问题
      * 21003 receipt无法通过验证
      * 21004 提供的shared secret不匹配你账号中的shared secret
      * 21005 receipt服务器当前不可用
      * 21006 receipt合法，但是订阅已过期。服务器接收到这个状态码时，receipt数据仍然会解码并一起发送
      * 21007 receipt是Sandbox receipt，但却发送至生产系统的验证服务
      * 21008 receipt是生产receipt，但却发送至Sandbox环境的验证服务
     */
    public function acurl($receipt_data, $sandbox=0){

        //小票信息
        //$POSTFIELDS = array("receipt-data" => $receipt_data);
        //$POSTFIELDS = json_encode($POSTFIELDS);
        $POSTFIELDS=$receipt_data;
//print_r($POSTFIELDS);exit;
        //正式购买地址 沙盒购买地址
        $url_buy     = "https://buy.itunes.apple.com/verifyReceipt";    
        $url_sandbox = "https://sandbox.itunes.apple.com/verifyReceipt";
        $url = $sandbox ? $url_sandbox : $url_buy;
        //简单的curl
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $POSTFIELDS);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        $result = curl_exec($ch);
        curl_close($ch);
        //print_r($result);exit;
        return $result;
    }


    
    


    //ios充值验证
    public function shaxiang(){
        $info=$this->chektoken();//检测用户token
        if(!$info){
            return json_encode(['code' =>2, 'msg'=>'请登录' ]);
        }
        $request = Request();
        $res = $request->param();
        $receipt    = new ReceiptModel();
        $product    = new ProductModel();
        $producth    = new ProductHaveModel();
        $User       = new UserModel();
        $receipt_data = $res['receipt_data'];//64位编码
        $product_id = $res['product_id'];//订单id
        $transaction_id = $res['transaction_id'];//订单号
        $res['type']=$res['type'] ? $res['type'] : 0 ;
        /*$timetxt = date("d").":". $receipt_data."--".$product_id."---".$transaction_id."\r\n";
        // 写日志
        $bruce=fopen("/home/wwwroot/fapiao/public/uploads/file/" .date("y-m-d") . ".txt","ab+"); //打开日志文件
        if(!$bruce)
        {
           echo'文件不存在';
           exit;
        }
        fwrite($bruce,$timetxt);
        fclose($bruce);*/
        //查询此此订单是否已使用
        $ss=$receipt->getInfo(['outtradeno'=>$transaction_id]);
        if($ss){
            return $this->json_error('购买失败此订单已支付完成或过期');
        }
        //验证参数
        if (strlen($receipt_data)<20){
            return $this->json_error('参数非法');
        }
        //请求验证
        $html = $this->acurl($receipt_data,$sandbox = false);
        $data = json_decode($html,1);

        if($data['status']=='21005'){
            return $this->json_error('receipt服务器当前不可用');
        }
        //如果是沙盒数据 则验证沙盒模式
        if($data['status']=='21007'){
            //请求验证
            $html = $this->acurl($receipt_data, $sandbox=1);
            $data = json_decode($html,1);
            $data['sandbox'] = '1';
        }
        if (isset($_GET['debug'])) {
            exit(json_encode($data));
        }
        $check=0;
        for($i=0;$i<count($data['receipt']['in_app']);$i++){
            if($transaction_id==$data['receipt']['in_app'][$i]['transaction_id']){
                $check=1;
                if($data['receipt']['in_app'][$i]['product_id'] != $product_id){
                    return $this->json_error('此订单信息错误！');
                }
                break;
            }
        }
        if($check==0){
            return $this->json_error('此订单不合法！');
        }
        if($data['status']==0){
            if($res['type']==1){
                $rqq=$producth->getInfo(['appleid'=>$product_id]);
                $arr=[
                    'uid'=>$info['id'],
                    'productid'=>$rqq['id'],//商品id
                    'money'=>$rqq['rulprice'],//价格
                    'pattern'=>'ios内购',
                    'source'=>'ios',//来源
                    'outtradeno'=>$transaction_id,//订单号
                    'comment'=>json_encode($data),
                    'receipt'=>$receipt_data,
                    'ctime'=>date('Y-m-d H:i:s',time()),
                    'type'=>1
                ];
                //写入订单表
                $receipt->getAdd($arr);
                $receipt->updatedatas(['state'=>1,'etime'=>date('Y-m-d H:i:s',time())],['outtradeno'=>$transaction_id]);
                $num=$info['frequency']+$rqq['number'];
                $zong=$info['totalnum']+$rqq['number'];
                $User->updatedatas(['frequency' => $num, 'totalnum' => $zong], ['id'=>$info['id']]);//修改用户次数
            }else{
                $rqq=$product->getInfo(['appleid'=>$product_id]);
                $arr=[
                    'uid'=>$info['id'],
                    'productid'=>$rqq['id'],//商品id
                    'money'=>$rqq['rulprice'],//价格
                    'pattern'=>'ios内购',
                    'source'=>'ios',//来源
                    'outtradeno'=>$transaction_id,//订单号
                    'comment'=>json_encode($data),
                    'receipt'=>$receipt_data,
                    'ctime'=>date('Y-m-d H:i:s',time())
                ];
                //写入订单表
                $receipt->getAdd($arr);
                $receipt->updatedatas(['state'=>1,'etime'=>date('Y-m-d H:i:s',time())],['outtradeno'=>$transaction_id]);
                //获取支付的订单的商品id，给用户添加会员周期
                if($info['uvip']==0){
                    //不是会员，修改会员时间和vip状态
                    $start_time=time();
                }else{
                    $start_time=strtotime($info['totime']);
                }
                if (!$rqq) {
                    return $this->json_error('订单不存在');
                }
                $time=date('Y-m-d H:i:s',strtotime("+".$rqq['number']." month",$start_time ));
                $num=$info['frequency']+$rqq['frequency'];
                $zong=$info['totalnum']+$rqq['frequency'];
                $User->updatedatas(['uvip'=>1,'totime'=>$time,'frequency' => $num, 'totalnum' => $zong],['id'=>$info['id']]);//修改用户vip信息
            }
            return $this->json_success('购买成功');
        }else{
            return $this->json_error('购买失败3');
        }
    }

    //商品列表
    public function goodlist(){
        $info=$this->chektoken();//检测用户token
        $product    = new ProductModel();
        $receipt    = new ReceiptModel();
        $where=['state'=>0];
        $res=$product->getList($where);
        if(!$info){
            array_pop($res);
            return json_encode(['code'=>0,'msg'=>'ok','result'=>$res]);
        }else{
            $es=$receipt->getList(['uid'=>$info['id'],'state'=>1]);
            if($es){
                array_pop($res);
                return json_encode(['code'=>0,'msg'=>'ok','result'=>$res]);
            }else{
                array_shift($res);
                return json_encode(['code'=>0,'msg'=>'ok','result'=>$res]);
            }
        }
    }


    //商品列表
    public function xgoodlist(){
        $product    = new ProductModel();
        $where=['state'=>0];
        $res=$product->getList($where);
        return json_encode(['code'=>0,'msg'=>'ok','result'=>$res]);
    }


    //沙箱测试
    public function test(){
        $receipt_data='MIJpkwYJKoZIhvcNAQcCoIJphDCCaYACAQExCzAJBgUrDgMCGgUAMIJZNAYJKoZIhvcNAQcBoIJZJQSCWSExglkdMAoCAQgCAQEEAhYAMAoCARQCAQEEAgwAMAsCAQECAQEEAwIBADALAgELAgEBBAMCAQAwCwIBDgIBAQQDAgFrMAsCAQ8CAQEEAwIBADALAgEQAgEBBAMCAQAwCwIBGQIBAQQDAgEDMAwCAQoCAQEEBBYCNCswDQIBDQIBAQQFAgMB1lUwDQIBEwIBAQQFDAMxLjAwDgIBCQIBAQQGAgRQMjUzMA8CAQMCAQEEBwwFMS40LjEwGAIBBAIBAgQQ17BQWqu4lAOTCgndTSCPkTAbAgEAAgEBBBMMEVByb2R1Y3Rpb25TYW5kYm94MBsCAQICAQEEEwwRY29tLnlpeW91Lmludm9pY2UwHAIBBQIBAQQUHJX11LxC3FtHbHVPK0bBJ8PYWcswHgIBDAIBAQQWFhQyMDIwLTAzLTExVDAzOjU2OjI3WjAeAgESAgEBBBYWFDIwMTMtMDgtMDFUMDc6MDA6MDBaMDoCAQcCAQEEMrvulCDaTTQ9FWbMXBC8njEfSv24zGlpygf43Mrr499niwBLYTRbZplKBF03oBehQNkfMFMCAQYCAQEES8vj86LNha6Mjvw0PnSK9eVfDerKa3SlcQMp4tsrr1VJQUngLpMkuDJDZPo9oLgCVTsIdNa/me7RrQO4bsChIMpWHdIoJzT32ilfzzCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2MzY0MDM1NTgwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjQwMzU1ODAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA1OjIyOjM3WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA1OjIyOjM3WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2MzY0NDYzMDQwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjQ0NjMwNDAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA2OjQ5OjUzWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA2OjQ5OjUzWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1MDMxMDcwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjUwMzEwNzAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA4OjIyOjI4WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA4OjIyOjI4WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2MDExMzkwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjYwMTEzOTAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDEwOjUyOjEyWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDEwOjUyOjEyWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2MjU5NjcwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjYyNTk2NzAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDExOjM1OjM5WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDExOjM1OjM5WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2MzY5OTUwNTUwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjk5NTA1NTAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDA3OjIzOjUwWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDA3OjIzOjUwWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2MzY5OTUxMTQwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjk5NTExNDAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDA3OjI0OjAyWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDA3OjI0OjAyWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2MzY5OTU3MzkwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjk5NTczOTAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDA3OjI1OjExWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDA3OjI1OjExWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2MzcxMzA5MDMwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzEzMDkwMzAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDExOjAwOjEwWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDExOjAwOjEwWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2MzcxMzEwMTEwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzEzMTAxMTAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDExOjAxOjE1WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDExOjAxOjE1WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2MzcxMzQ0NzkwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzEzNDQ3OTAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDExOjA4OjQzWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDExOjA4OjQzWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2MzcxMzQ1ODIwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzEzNDU4MjAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDExOjA5OjA4WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDExOjA5OjA4WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2MzcxNDc5MDkwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzE0NzkwOTAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDExOjM0OjU4WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDExOjM0OjU4WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2MzcxNDkzNzcwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzE0OTM3NzAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDExOjM4OjI5WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDExOjM4OjI5WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2Mzc0NTEyNDMwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzQ1MTI0MzAfAgIGqAIBAQQWFhQyMDIwLTAzLTExVDAzOjQ3OjE3WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTExVDAzOjQ3OjE3WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2Mzc0NTE1MjkwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzQ1MTUyOTAfAgIGqAIBAQQWFhQyMDIwLTAzLTExVDAzOjQ4OjM1WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTExVDAzOjQ4OjM1WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2Mzc0NTM3MjIwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzQ1MzcyMjAfAgIGqAIBAQQWFhQyMDIwLTAzLTExVDAzOjUyOjEzWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTExVDAzOjUyOjEzWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2Mzc0NTQxNzEwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzQ1NDE3MTAfAgIGqAIBAQQWFhQyMDIwLTAzLTExVDAzOjUzOjQ1WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTExVDAzOjUzOjQ1WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2Mzc0NTQ1NTkwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzQ1NDU1OTAfAgIGqAIBAQQWFhQyMDIwLTAzLTExVDAzOjU1OjI0WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTExVDAzOjU1OjI0WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAxMBsCAganAgEBBBIMEDEwMDAwMDA2Mzc0NTQ3MDUwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzQ1NDcwNTAfAgIGqAIBAQQWFhQyMDIwLTAzLTExVDAzOjU2OjI3WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTExVDAzOjU2OjI3WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY0MDI4MzIwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjQwMjgzMjAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA1OjE5OjE0WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA1OjE5OjE0WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY0MDMwNzcwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjQwMzA3NzAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA1OjIwOjEyWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA1OjIwOjEyWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY0MDc5NTYwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjQwNzk1NjAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA1OjMzOjU0WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA1OjMzOjU0WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY0MTgyNzEwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjQxODI3MTAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA1OjU2OjMyWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA1OjU2OjMyWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1MDIzMDMwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjUwMjMwMzAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA4OjE5OjUwWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA4OjE5OjUwWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1MDczNzgwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjUwNzM3ODAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA4OjI3OjI2WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA4OjI3OjI2WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1MjkwNTQwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjUyOTA1NDAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA4OjU5OjE4WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA4OjU5OjE4WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1MzExNzcwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjUzMTE3NzAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA5OjAzOjAxWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA5OjAzOjAxWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1NDY3MjUwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjU0NjcyNTAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA5OjI0OjA3WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA5OjI0OjA3WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1NzQ4NDYwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjU3NDg0NjAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDEwOjAwOjExWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDEwOjAwOjExWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1NzU3MzMwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjU3NTczMzAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDEwOjAzOjQwWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDEwOjAzOjQwWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1OTY3MDcwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjU5NjcwNzAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDEwOjQ0OjU2WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDEwOjQ0OjU2WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1OTc3NzYwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjU5Nzc3NjAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDEwOjQ3OjA5WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDEwOjQ3OjA5WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1OTk4ODgwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjU5OTg4ODAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDEwOjUwOjU1WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDEwOjUwOjU1WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2MDczOTMwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjYwNzM5MzAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDExOjAxOjUzWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDExOjAxOjUzWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2MjA0OTQwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjYyMDQ5NDAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDExOjI2OjUxWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDExOjI2OjUxWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY5MTI5MzcwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjkxMjkzNzAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDAzOjE3OjM3WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDAzOjE3OjM3WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY5MTUzNDIwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjkxNTM0MjAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDAzOjI2OjI3WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDAzOjI2OjI3WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY5MjIwNDkwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjkyMjA0OTAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDAzOjQyOjE4WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDAzOjQyOjE4WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY5MjM0ODkwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjkyMzQ4OTAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDAzOjQ3OjMwWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDAzOjQ3OjMwWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY5Mjc5MDUwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjkyNzkwNTAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDA0OjAwOjQzWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDA0OjAwOjQzWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzY5OTQ5NDEwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjk5NDk0MTAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDA3OjIzOjM5WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDA3OjIzOjM5WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzcxMjU3MzUwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzEyNTczNTAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDEwOjQ5OjQ0WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDEwOjQ5OjQ0WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAyMBsCAganAgEBBBIMEDEwMDAwMDA2MzcxMjkzMDQwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzEyOTMwNDAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDEwOjU2OjQ5WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDEwOjU2OjQ5WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY0MDQ5MzAwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjQwNDkzMDAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA1OjI2OjUxWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA1OjI2OjUxWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY0MDU0MTkwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjQwNTQxOTAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA1OjI3OjQ5WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA1OjI3OjQ5WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY0MDU2NDMwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjQwNTY0MzAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA1OjI4OjU2WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA1OjI4OjU2WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY0NzUyNjkwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjQ3NTI2OTAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA3OjQyOjM3WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA3OjQyOjM3WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1MDQ1NjkwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjUwNDU2OTAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA4OjI0OjI4WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA4OjI0OjI4WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1NTgwMDAwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjU1ODAwMDAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA5OjM3OjU0WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA5OjM3OjU0WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1Njc4MzcwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjU2NzgzNzAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDA5OjQ4OjI2WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDA5OjQ4OjI2WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1ODMxODcwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjU4MzE4NzAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDEwOjE2OjI5WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDEwOjE2OjI5WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY1OTA0MzAwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjU5MDQzMDAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDEwOjMwOjU1WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDEwOjMwOjU1WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2MTAxMDMwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjYxMDEwMzAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDExOjA2OjU0WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDExOjA2OjU0WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2MTMwOTYwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjYxMzA5NjAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDExOjEyOjMxWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDExOjEyOjMxWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2MTU1ODEwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjYxNTU4MTAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDExOjE3OjE2WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDExOjE3OjE2WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2MTcyMjgwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjYxNzIyODAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDExOjIwOjQ1WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDExOjIwOjQ1WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2MTk3MjIwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjYxOTcyMjAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDExOjI0OjU4WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDExOjI0OjU4WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2MjE4ODcwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjYyMTg4NzAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDExOjI5OjE1WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDExOjI5OjE1WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2NDY0OTIwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjY0NjQ5MjAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDEyOjA4OjM2WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDEyOjA4OjM2WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2NTUyMjAwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjY1NTIyMDAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDEyOjIxOjI0WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDEyOjIxOjI0WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2NTcwMzgwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjY1NzAzODAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDEyOjI0OjIzWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDEyOjI0OjIzWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2NTkzMTUwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjY1OTMxNTAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDEyOjI3OjU2WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDEyOjI3OjU2WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY2NjQwNTAwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjY2NDA1MDAfAgIGqAIBAQQWFhQyMDIwLTAzLTA5VDEyOjMzOjM0WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTA5VDEyOjMzOjM0WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzY5MDA4MjIwGwICBqkCAQEEEgwQMTAwMDAwMDYzNjkwMDgyMjAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDAyOjM0OjU0WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDAyOjM0OjU0WjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzcxMzM5OTYwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzEzMzk5NjAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDExOjA2OjUzWjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDExOjA2OjUzWjCCAUkCARECAQEEggE/MYIBOzALAgIGrAIBAQQCFgAwCwICBq0CAQEEAgwAMAsCAgawAgEBBAIWADALAgIGsgIBAQQCDAAwCwICBrMCAQEEAgwAMAsCAga0AgEBBAIMADALAgIGtQIBAQQCDAAwCwICBrYCAQEEAgwAMAwCAgalAgEBBAMCAQEwDAICBqsCAQEEAwIBAjAMAgIGrgIBAQQDAgEAMAwCAgavAgEBBAMCAQAwDAICBrECAQEEAwIBADAPAgIGpgIBAQQGDAR2aXAzMBsCAganAgEBBBIMEDEwMDAwMDA2MzcxMzkxOTIwGwICBqkCAQEEEgwQMTAwMDAwMDYzNzEzOTE5MjAfAgIGqAIBAQQWFhQyMDIwLTAzLTEwVDExOjE3OjA0WjAfAgIGqgIBAQQWFhQyMDIwLTAzLTEwVDExOjE3OjA0WqCCDmUwggV8MIIEZKADAgECAggO61eH554JjTANBgkqhkiG9w0BAQUFADCBljELMAkGA1UEBhMCVVMxEzARBgNVBAoMCkFwcGxlIEluYy4xLDAqBgNVBAsMI0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zMUQwQgYDVQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTAeFw0xNTExMTMwMjE1MDlaFw0yMzAyMDcyMTQ4NDdaMIGJMTcwNQYDVQQDDC5NYWMgQXBwIFN0b3JlIGFuZCBpVHVuZXMgU3RvcmUgUmVjZWlwdCBTaWduaW5nMSwwKgYDVQQLDCNBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQClz4H9JaKBW9aH7SPaMxyO4iPApcQmyz3Gn+xKDVWG/6QC15fKOVRtfX+yVBidxCxScY5ke4LOibpJ1gjltIhxzz9bRi7GxB24A6lYogQ+IXjV27fQjhKNg0xbKmg3k8LyvR7E0qEMSlhSqxLj7d0fmBWQNS3CzBLKjUiB91h4VGvojDE2H0oGDEdU8zeQuLKSiX1fpIVK4cCc4Lqku4KXY/Qrk8H9Pm/KwfU8qY9SGsAlCnYO3v6Z/v/Ca/VbXqxzUUkIVonMQ5DMjoEC0KCXtlyxoWlph5AQaCYmObgdEHOwCl3Fc9DfdjvYLdmIHuPsB8/ijtDT+iZVge/iA0kjAgMBAAGjggHXMIIB0zA/BggrBgEFBQcBAQQzMDEwLwYIKwYBBQUHMAGGI2h0dHA6Ly9vY3NwLmFwcGxlLmNvbS9vY3NwMDMtd3dkcjA0MB0GA1UdDgQWBBSRpJz8xHa3n6CK9E31jzZd7SsEhTAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFIgnFwmpthhgi+zruvZHWcVSVKO3MIIBHgYDVR0gBIIBFTCCAREwggENBgoqhkiG92NkBQYBMIH+MIHDBggrBgEFBQcCAjCBtgyBs1JlbGlhbmNlIG9uIHRoaXMgY2VydGlmaWNhdGUgYnkgYW55IHBhcnR5IGFzc3VtZXMgYWNjZXB0YW5jZSBvZiB0aGUgdGhlbiBhcHBsaWNhYmxlIHN0YW5kYXJkIHRlcm1zIGFuZCBjb25kaXRpb25zIG9mIHVzZSwgY2VydGlmaWNhdGUgcG9saWN5IGFuZCBjZXJ0aWZpY2F0aW9uIHByYWN0aWNlIHN0YXRlbWVudHMuMDYGCCsGAQUFBwIBFipodHRwOi8vd3d3LmFwcGxlLmNvbS9jZXJ0aWZpY2F0ZWF1dGhvcml0eS8wDgYDVR0PAQH/BAQDAgeAMBAGCiqGSIb3Y2QGCwEEAgUAMA0GCSqGSIb3DQEBBQUAA4IBAQANphvTLj3jWysHbkKWbNPojEMwgl/gXNGNvr0PvRr8JZLbjIXDgFnf4+LXLgUUrA3btrj+/DUufMutF2uOfx/kd7mxZ5W0E16mGYZ2+FogledjjA9z/Ojtxh+umfhlSFyg4Cg6wBA3LbmgBDkfc7nIBf3y3n8aKipuKwH8oCBc2et9J6Yz+PWY4L5E27FMZ/xuCk/J4gao0pfzp45rUaJahHVl0RYEYuPBX/UIqc9o2ZIAycGMs/iNAGS6WGDAfK+PdcppuVsq1h1obphC9UynNxmbzDscehlD86Ntv0hgBgw2kivs3hi1EdotI9CO/KBpnBcbnoB7OUdFMGEvxxOoMIIEIjCCAwqgAwIBAgIIAd68xDltoBAwDQYJKoZIhvcNAQEFBQAwYjELMAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIEluYy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRYwFAYDVQQDEw1BcHBsZSBSb290IENBMB4XDTEzMDIwNzIxNDg0N1oXDTIzMDIwNzIxNDg0N1owgZYxCzAJBgNVBAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDKOFSmy1aqyCQ5SOmM7uxfuH8mkbw0U3rOfGOAYXdkXqUHI7Y5/lAtFVZYcC1+xG7BSoU+L/DehBqhV8mvexj/avoVEkkVCBmsqtsqMu2WY2hSFT2Miuy/axiV4AOsAX2XBWfODoWVN2rtCbauZ81RZJ/GXNG8V25nNYB2NqSHgW44j9grFU57Jdhav06DwY3Sk9UacbVgnJ0zTlX5ElgMhrgWDcHld0WNUEi6Ky3klIXh6MSdxmilsKP8Z35wugJZS3dCkTm59c3hTO/AO0iMpuUhXf1qarunFjVg0uat80YpyejDi+l5wGphZxWy8P3laLxiX27Pmd3vG2P+kmWrAgMBAAGjgaYwgaMwHQYDVR0OBBYEFIgnFwmpthhgi+zruvZHWcVSVKO3MA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAUK9BpR5R2Cf70a40uQKb3R01/CF4wLgYDVR0fBCcwJTAjoCGgH4YdaHR0cDovL2NybC5hcHBsZS5jb20vcm9vdC5jcmwwDgYDVR0PAQH/BAQDAgGGMBAGCiqGSIb3Y2QGAgEEAgUAMA0GCSqGSIb3DQEBBQUAA4IBAQBPz+9Zviz1smwvj+4ThzLoBTWobot9yWkMudkXvHcs1Gfi/ZptOllc34MBvbKuKmFysa/Nw0Uwj6ODDc4dR7Txk4qjdJukw5hyhzs+r0ULklS5MruQGFNrCk4QttkdUGwhgAqJTleMa1s8Pab93vcNIx0LSiaHP7qRkkykGRIZbVf1eliHe2iK5IaMSuviSRSqpd1VAKmuu0swruGgsbwpgOYJd+W+NKIByn/c4grmO7i77LpilfMFY0GCzQ87HUyVpNur+cmV6U/kTecmmYHpvPm0KdIBembhLoz2IYrF+Hjhga6/05Cdqa3zr/04GpZnMBxRpVzscYqCtGwPDBUfMIIEuzCCA6OgAwIBAgIBAjANBgkqhkiG9w0BAQUFADBiMQswCQYDVQQGEwJVUzETMBEGA1UEChMKQXBwbGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxFjAUBgNVBAMTDUFwcGxlIFJvb3QgQ0EwHhcNMDYwNDI1MjE0MDM2WhcNMzUwMjA5MjE0MDM2WjBiMQswCQYDVQQGEwJVUzETMBEGA1UEChMKQXBwbGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxFjAUBgNVBAMTDUFwcGxlIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDkkakJH5HbHkdQ6wXtXnmELes2oldMVeyLGYne+Uts9QerIjAC6Bg++FAJ039BqJj50cpmnCRrEdCju+QbKsMflZ56DKRHi1vUFjczy8QPTc4UadHJGXL1XQ7Vf1+b8iUDulWPTV0N8WQ1IxVLFVkds5T39pyez1C6wVhQZ48ItCD3y6wsIG9wtj8BMIy3Q88PnT3zK0koGsj+zrW5DtleHNbLPbU6rfQPDgCSC7EhFi501TwN22IWq6NxkkdTVcGvL0Gz+PvjcM3mo0xFfh9Ma1CWQYnEdGILEINBhzOKgbEwWOxaBDKMaLOPHd5lc/9nXmW8Sdh2nzMUZaF3lMktAgMBAAGjggF6MIIBdjAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUK9BpR5R2Cf70a40uQKb3R01/CF4wHwYDVR0jBBgwFoAUK9BpR5R2Cf70a40uQKb3R01/CF4wggERBgNVHSAEggEIMIIBBDCCAQAGCSqGSIb3Y2QFATCB8jAqBggrBgEFBQcCARYeaHR0cHM6Ly93d3cuYXBwbGUuY29tL2FwcGxlY2EvMIHDBggrBgEFBQcCAjCBthqBs1JlbGlhbmNlIG9uIHRoaXMgY2VydGlmaWNhdGUgYnkgYW55IHBhcnR5IGFzc3VtZXMgYWNjZXB0YW5jZSBvZiB0aGUgdGhlbiBhcHBsaWNhYmxlIHN0YW5kYXJkIHRlcm1zIGFuZCBjb25kaXRpb25zIG9mIHVzZSwgY2VydGlmaWNhdGUgcG9saWN5IGFuZCBjZXJ0aWZpY2F0aW9uIHByYWN0aWNlIHN0YXRlbWVudHMuMA0GCSqGSIb3DQEBBQUAA4IBAQBcNplMLXi37Yyb3PN3m/J20ncwT8EfhYOFG5k9RzfyqZtAjizUsZAS2L70c5vu0mQPy3lPNNiiPvl4/2vIB+x9OYOLUyDTOMSxv5pPCmv/K/xZpwUJfBdAVhEedNO3iyM7R6PVbyTi69G3cN8PReEnyvFteO3ntRcXqNx+IjXKJdXZD9Zr1KIkIxH3oayPc4FgxhtbCS+SsvhESPBgOJ4V9T0mZyCKM2r3DYLP3uujL/lTaltkwGMzd/c6ByxW69oPIQ7aunMZT7XZNn/Bh1XZp5m5MkL72NVxnn6hUrcbvZNCJBIqxw8dtk2cXmPIS4AXUKqK1drk/NAJBzewdXUhMYIByzCCAccCAQEwgaMwgZYxCzAJBgNVBAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkCCA7rV4fnngmNMAkGBSsOAwIaBQAwDQYJKoZIhvcNAQEBBQAEggEAaAZPMX+OUp6YJfE6LaAXKCyTvqcj1BkC+znoW/Ih1G3PH4esQ149vheDjFAZCtAOtW1sxffZxLNm16mFo4PbP27K6d6EYxWL8fmRSd1bFv1Eu2pMyOBYAaonNdE1KiyYArH5l3O0uuHzsRcevKiyThzfnneOcCglujuBmcN6Ic84a5HEkZtF8sk89ChpxpNViJfKRrRqkw4zevTFLrAezfDQe9vPo6GzcgGNUtm730IiIBZIKJ5QT2qUgQebVqhfeHijXZNruxV5AktuxFwt2LtxKp6H3Lywlr5byLOVZzEmncQ+wyax8ZGgBvfFcWIcGVsOkHqGGLbQ3pSfULTJ3g==';
        $html = $this->acurl($receipt_data,$sandbox = false);
        $data = json_decode($html,1);
        if($data['status']=='21007'){
            //请求验证
            //print_r($data);exit;
            $html = $this->acurl($receipt_data, $sandbox=1);
            $data = json_decode($html,1);
            $data['sandbox'] = '1';
        }
        print_r($data);exit;
    }


    //购买次数列表
    public function cinumber(){
        $res=Db::table('fp_product_number')->where(['state'=>0])->select();
        return json_encode(['code'=>0,'msg'=>'ok','result'=>$res]);
    }





















	
	
}
?>